name: rna_seq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - attrs
  - fastqc
  - picard
  - multiqc
  - star
  - samtools
  - pigz
  - subread
  - bedops
  - gatk
  - bcftools
  - pip:
    - dmpy
